[package]
authors = [
    "Aaron Turon <aturon@mozilla.com>",
    "Yoshua Wuyts <yoshuawuyts@gmail.com>",
    "Wonwoo Choi <chwo9843@gmail.com>",
]
description = "HttpService server that uses Hyper as backend"
edition = "2018"
license = "MIT OR Apache-2.0"
name = "http-service-hyper"
repository = "https://github.com/rust-net-web/http-service"
version = "0.1.0"

[dependencies]
http = "0.1"
http-service = "0.1.5"
hyper = "0.12.27"

[dependencies.futures-preview]
features = ["compat"]
version = "0.3.0-alpha.14"
