[package]
authors = ["Aaron Turon <aturon@mozilla.com>"]
description = "Types and traits for standardizing async HTTP services"
repository = "https://github.com/rust-net-web/http-service"
edition = "2018"
license = "MIT OR Apache-2.0"
name = "http-service"
version = "0.1.5"

[workspace]
members = ["http-service-hyper", "http-service-mock"]

[dependencies]
bytes = "0.4.12"
http = "0.1.17"

[dependencies.futures-preview]
version = "0.3.0-alpha.14"
