[package]
authors = ["Aaron Turon <aturon@mozilla.com>"]
description = "Types and traits for standardizing async HTTP services"
repository = "https://github.com/rustasync/http-service"
documentation = "https://docs.rs/http-service"
keywords = ["http-service", "http", "web", "async"]
categories = [
  "network-programming",
  "asynchronous",
  "web-programming::http-server"
]
readme = "README.md"
edition = "2018"
license = "MIT OR Apache-2.0"
name = "http-service"
version = "0.3.1"

[workspace]
members = ["http-service-hyper", "http-service-lambda", "http-service-mock"]

[dependencies]
bytes = "0.4.12"
http = "0.1.18"

[dev-dependencies]
http-service-hyper = { version = "0.3.1", path = "./http-service-hyper" }
tokio = "0.2.0-alpha.4"

[dependencies.futures-preview]
version = "0.3.0-alpha.18"

[patch.crates-io]
http-service = { path = "." }
http-service-hyper = { path = "./http-service-hyper" }
http-service-mock = { path = "./http-service-mock" }
tide = { git = "https://github.com/rustasync/tide", branch = "master" }
